### ISSUE TITLE
Use Clarify to parse 2016 general election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-sc#14]
Using our [clarify](https://github.com/openelections/clarify) Python library, parse the precinct-level results from the 2016 general election located [here](http://www.enr-scvotes.org/SC/64658/184701/en/summary.html).

The goal is to generate a CSV file named `20161108__sc__general__precinct.csv`` that contains precinct-level results for the entire state for the following offices: President, U.S. Senate, U.S. House, State Senate and State House.

The CSV should have the following columns:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

The `district` column is for U.S. House, State Senate and State House.

**Comment by tamilyn** [comment]
I'll work on this.
