### ISSUE TITLE
2006 primaries

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-sc#2]
[Electronic PDFs](http://www.scvotes.org/2006/06/15/2006_primary_results) that can be converted using Tabula.

**Comment by danhillreports** [comment]
Would you like the county results for [statewide](http://www.scvotes.org/files/06primaryOfficial/RepublicanStatewide.pdf) and [district offices](http://www.scvotes.org/files/06primaryOfficial/RepublicanbyMulti-County.pdf) combined in one file (like `20060613__sc__republican__primary__county.csv`)?

Would you rather have the [precinct by county results](http://www.scvotes.org/files/06primaryOfficial/RepublicanbyCounty.pdf) as one file (`20060613__sc__republican__primary__precincts.csv`) or separate files for each county (`20060613__sc__republican__primary__abbeville__precinct.csv`)?

**Comment by dwillis** [comment]
I think I'd like a single county-level results file, but separate precinct-level files for each county, but whatever is easiest for you works for us.

**Comment by danhillreports** [comment]
@dwillis I think this issue should still be open because we don't have 2006 primary precincts

**Comment by dwillis** [comment]
You are right.
