### ISSUE TITLE
2006 primary runoffs

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-sc#3]
[Electronic PDFs](http://www.scvotes.org/2006/07/26/2006_primary_runoff_results) that can be converted using Tabula.

**Comment by danhillreports** [comment]
I can take this, would these be the files?

* `20060627__sc__democratic__primary-runoff__county.csv`
* `20060627__sc__republican__primary-runoff__county.csv`
* `20060627__sc__{party}__primary-runoff__{county}__precinct.csv` for each county, each party

**Comment by dwillis** [comment]
just change primary-runoff to primary__runoff and that's great. Thanks!
